kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-repl1
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  io_priority: "high"
  cow_ondemand: "true"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-repl1-encrypted
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  io_priority: "high"
  cow_ondemand: "true"
  secure: "true"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-repl2
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  io_profile: "db_remote"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-repl2-encrypted
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  io_profile: "db_remote"
  secure: "true"
allowVolumeExpansion: true
