kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-node-specific-sc
  labels:
    app: postgres
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  placement_strategy: "node-specific"
allowVolumeExpansion: true
