apiVersion: portworx.io/v1beta2
kind: VolumePlacementStrategy
metadata:
  name: node-specific
spec:
  replicaAffinity:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - "$NODE"
