kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vps-test
  namespace: postgres
spec:
  storageClassName: px-node-specific-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
